# Generated by Django 3.0 on 2019-12-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentary_title', models.CharField(default='kkkk', max_length=200)),
                ('documentary_creator1', models.CharField(max_length=100)),
                ('documentary_creator2', models.CharField(default='None', max_length=100)),
                ('documentary_synopsis', models.CharField(max_length=1000)),
                ('documentary_poster', models.FileField(upload_to='')),
                ('documentary_release_date', models.DateField(default='0000', verbose_name='Date')),
                ('documentary_budget', models.IntegerField()),
                ('documentary_gross', models.IntegerField()),
                ('documentary_genre', models.CharField(default='Action', max_length=100)),
                ('documentary_rating', models.FloatField()),
            ],
        ),
    ]
