# Generated by Django 3.0 on 2019-12-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_director', models.CharField(max_length=1000)),
                ('movie_synopsis', models.CharField(max_length=1000)),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_poster', models.FileField(upload_to='')),
                ('movie_thumbnail', models.FileField(default='Planet Earth thumbnail', upload_to='')),
                ('movie_release_date', models.DateField(default='0000', verbose_name='Date')),
                ('movie_budget', models.IntegerField()),
                ('movie_gross', models.IntegerField()),
                ('movie_genre', models.CharField(max_length=100)),
                ('movie_quality', models.CharField(max_length=100)),
                ('movie_rating', models.FloatField()),
                ('movie_video', models.FileField(upload_to='')),
                ('movie_subtitles', models.FileField(default='Planet Earth Subtitles', upload_to='')),
            ],
        ),
    ]
